name: Push check

on:
  push:
    branches-ignore:
      - dev
    tags-ignore:
      - v*

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ github.ref_name }}
